### ISSUE TITLE
Convert React router project to NextJs 14

### ISSUE THREAD

**Issue by satyam8932** [satnaing/shadcn-admin#13]
Hey, I have seen a job post on upwork regarding the conversion of this react app to nextjs 14 app router 
Here : https://www.upwork.com/jobs/~01a65b13c48a1415ae

I can help you to do the job in cost effective budget, let me know if you are interested then we can work through Upwork.

Thanks
Satyam

**Comment by satnaing** [comment]
Sounds interesting.
You can send an email and we can discuss it. (satnaingdev@gmail.com)

**Comment by anupjha** [comment]
I think @shadcn-ui is already working on it.

**Comment by anupjha** [comment]
@satnaing Check this tweet https://x.com/shadcn/status/1795920507851911443
Also he has released few charts too. https://ui.shadcn.com/charts

**Comment by satnaing** [comment]
Didn't notice that. Thanks.
I'll keep an eye on that. 👀

**Comment by satyam8932** [comment]
Hey @satnaing is the job on Upwork still accepting proposal as I'm willing to work with you.
Let me know if you have openings for conversion of react router to next js router
