### ISSUE TITLE
Unable to Paste OTP Using Ctrl + V in Input Field

### ISSUE THREAD

**Issue by Abhishekpatel123** [satnaing/shadcn-admin#16]
When attempting to paste a 5-digit OTP into a 6-digit input field using Ctrl + V, the input becomes unresponsive upon typing the 6th digit. The input field stops accepting any further input, and only switching between input fields works. This issue prevents users from easily entering their OTP.

**Comment by satnaing** [comment]
Thanks for pointing this out. 
I didn't notice this issue existed.

Turns out it just needs one more condition in the pin-input logic.
It's gonna be fixed in #17
