### ISSUE TITLE
Add `Users` page

### ISSUE THREAD

**Issue by satnaing** [satnaing/shadcn-admin#26]

**Comment by WenLonG12345** [comment]
Hi, @satnaing . Thanks for this amazing project! <3
Can I contribute in this project on this task? Maybe you can let me know the design in your mind, and I can create a PR on this?

**Comment by satnaing** [comment]
Hello @WenLonG12345!
I was busy and didn't notice your comment.
I already have some progress for this task by the time you dropped the comment.

However, thanks for your interest in contributing to this project.
I'll also add some contribution guidelines for this project in the future.
So, stay tuned!!!
