### ISSUE TITLE
sticky top-menu

### ISSUE THREAD

**Issue by lsdev200** [satnaing/shadcn-admin#4]
Hello, greetings!

I would like assistance in creating a sticky top bar for your website. Could you please help me with that?

Thank you.

printScreen:
https://prnt.sc/mfILYH2qONnB

**Comment by satnaing** [comment]
Hello @lsdev200,
I'm not sure this helps.
If I ever want to have a sticky top nav bar, I'd do something like this.

```tsx
// file: src/pages/dashboard/index.tsx

export default function Dashboard() {
  return (
    <Layout>
      {/* ===== Top Heading ===== */}
      <LayoutHeader className='fixed z-10 w-[calc(100%-16rem)] shadow'> {/* <= add these classes */}
        <TopNav links={topNav} />
        <div className='ml-auto flex items-center space-x-4'>
          <Search />
          <ThemeSwitch />
          <UserNav />
        </div>
      </LayoutHeader>

      {/* ===== Main ===== */}
      <LayoutBody className='mt-16 space-y-4'> {/* <= add mt-16 class */}
      {/* other codes */}
  )
}
```

**Comment by lsdev200** [comment]
Hi Sat Naing,

I hope this email finds you well. I wanted to reach out and express my
gratitude for sharing the code snippet for implementing a sticky top nav
bar. I'm pleased to inform you that I have successfully integrated the code
into my project, and it is working perfectly as intended.

Your assistance has been invaluable, and I truly appreciate your help in
guiding me through this process. If I have any further questions or need
additional support in the future, I will not hesitate to reach out.

Thank you once again for your support and for sharing your expertise with
me.

Best regards,

Ls Dev
