### ISSUE TITLE
 Vite dev mode loads all icon chunks with 3.19.0 (React)

### ISSUE THREAD

**Issue by ngocson092** [satnaing/shadcn-admin#54]
This repo is very good, but it's slow. I found the cause in tabler-icons and have fixed it following the instructions from this link. Please update it.
https://github.com/tabler/tabler-icons/issues/1233#issuecomment-2428245119

**Comment by satnaing** [comment]
Thank you so much for this. @ngocson092 
I overlooked the root cause.
