### ISSUE TITLE
Pagination Adjustment Bug

### ISSUE THREAD

**Issue by inboxsphere** [satnaing/shadcn-admin#65]
Description:
When using the pagination feature on the following pages:

[Tasks](https://shadcn-admin.netlify.app/tasks)
[Users](https://shadcn-admin.netlify.app/users)
There is an issue with adjusting the page size.

After changing the page size once, attempting to adjust it again results in the page jumping to the top.
This behavior makes it impossible to modify the page size multiple times without scrolling back down to the pagination controls.
Steps to Reproduce:
Navigate to the [Tasks](https://shadcn-admin.netlify.app/tasks) or [Users](https://shadcn-admin.netlify.app/users) page.
Scroll to the bottom of the page and adjust the page size in the pagination controls.
Attempt to change the page size again.
Expected Behavior:
The page size should update without forcing the page to scroll to the top.

Actual Behavior:
The page jumps to the top, interrupting the adjustment process.

Suggested Fix:
Investigate the event handling for pagination adjustments and ensure the page does not scroll to the top when the page size is changed.

Let me know if you need additional information or steps for debugging!

**Comment by satnaing** [comment]
Thanks for pointing this out.
I just made a fix PR for this.

**Comment by inboxsphere** [comment]
cool, man. this project is really helpful
