### ISSUE TITLE
User and Request pages are blank.

### ISSUE THREAD

**Issue by loopmatix-dev** [satnaing/shadcn-admin#9]
Nice work, its really helpful. I would like to know when you are planning to add User & requests pages? I am building side project. So I would like to use this starter. 

Thanks

**Comment by satnaing** [comment]
I'm a bit busy right now so I can't guarantee when those pages will be done.
Within the next week, I could build `Users` or `Chat` or both pages though.

**Comment by 3omer** [comment]
How we can contribute? I mean is there any design files we can use?

**Comment by satnaing** [comment]
Thanks for your interest in contributing to this project. @3omer 
The thing is that I don't have any design files to follow and develop.
I just made a draft UI in Figma and made it happen with the actual codes based on my experience. (eg: new Chat Page #21)
However, I tried to make the UI as simple and minimal as possible just like the original Shadcn UI. 
Maybe you can follow the styles of [the ShadcnUI Figma](https://www.figma.com/community/file/1203061493325953101).
